#!/bin/bash

git submodule update --init --recursive

sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt-get install -y zsh curl git bat make gcc ripgrep unzip git xclip neovim build-essential libreadline-dev unzip lua5.4 luarocks
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl -sS https://starship.rs/install.sh | sh

# ZSH autosuggestions
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi

# ZSH Syntax Highlighting
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi

# ZSH History Substring Search
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-history-substring-search" ]; then
  git clone https://github.com/zsh-users/zsh-history-substring-search "$ZSH_CUSTOM/plugins/zsh-history-substring-search"
fi


echo "stowing..."
for d in $(ls -d */ | cut -f1 -d '/'); do
  (stow --adopt "$d")
done

git restore .

