######################
### DESIGN CHANGES ###
######################

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set -g allow-rename on

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# RGB color palette

set -g default-terminal "screen-256color" 
set-option -sa terminal-overrides ",xterm-256color:RGB"

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# messages
set -g message-style 'fg=colour232 bg=colour16 bold'

set -g @plugin 'tmux-plugins/tmux-sensible'

# Run tmux plugins
run '~/.tmux/plugins/tpm/tpm'
